spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.226.128/OMSys?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
logging:
  pattern:
    console: "%d - %msg%n"
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl